import { generateLink } from "@/application/features/pdfAntrag/generate-link";
import { Elternteil, Variante } from "@/monatsplaner";

export const pdfVersionZwischenApril2024UndApril2025 = {
  start: new Date("2024-04-01"),
  end: new Date("2025-03-31"),
  pdfFileAntragPath: generateLink({
    familienportalPath:
      "/blob/268174/b91612ebb7236fe35844bef6de51bf1e/von2024-04-01bis2025-03-31-antrag-dhu7g-jp-data.pdf",
    relativePath: "/documents/von2024-04-01bis2025-03-31_seite.pdf",
  }),
  pdfFileSeitePath: generateLink({
    familienportalPath:
      "/blob/268176/50f856ad3793e483be6672ddaf7ce772/von2024-04-01bis2025-03-31-seite-cark7are-data.pdf",
    relativePath: "/documents/von2024-04-01bis2025-03-31_seite.pdf",
  }),
  fieldNames: {
    vorname: {
      [Elternteil.Eins]: "txt.vorname2b",
      [Elternteil.Zwei]: "txt.vorname2b 1",
    },
    [Variante.Basis]: {
      [Elternteil.Eins]: [
        "cb_BG_1",
        "cb_BG_2",
        "cb_BG_3",
        "cb_BG_4",
        "cb_BG_5",
        "cb_BG_6",
        "cb_BG_7",
        "cb_BG_8",
        "cb_BG_9",
        "cb_BG_10",
        "cb_BG_11",
        "cb_BG_12",
        "cb_BG_13",
        "cb_BG_14",
      ],
      [Elternteil.Zwei]: [
        "cb_BG_20",
        "cb_BG_21",
        "cb_BG_22",
        "cb_BG_23",
        "cb_BG_24",
        "cb_BG_25",
        "cb_BG_26",
        "cb_BG_27",
        "cb_BG_28",
        "cb_BG_29",
        "cb_BG_30",
        "cb_BG_31",
        "cb_BG_32",
        "cb_BG_33",
      ],
    },
    [Variante.Plus]: {
      [Elternteil.Eins]: [
        "cb_E+_1",
        "cb_E+_2",
        "cb_E+_3",
        "cb_E+_4",
        "cb_E+_5",
        "cb_E+_6",
        "cb_E+_7",
        "cb_E+_8",
        "cb_E+_9",
        "cb_E+_10",
        "cb_E+_11",
        "cb_E+_12",
        "cb_E+_13",
        "cb_E+_14",
        "cb_E+_15",
        "cb_E+_16",
        "cb_E+_17",
        "cb_E+_18",
        "cb_E+_19",
        "cb_E+_20",
        "cb_E+_21",
        "cb_E+_22",
        "cb_E+_23",
        "cb_E+_24",
        "cb_E+_25",
        "cb_E+_26",
        "cb_E+_27",
        "cb_E+_28",
        "cb_E+_29",
        "cb_E+_30",
        "cb_E+_31",
        "cb_E+_32",
      ],
      [Elternteil.Zwei]: [
        "cb_E+_34",
        "cb_E+_35",
        "cb_E+_36",
        "cb_E+_37",
        "cb_E+_38",
        "cb_E+_39",
        "cb_E+_40",
        "cb_E+_41",
        "cb_E+_42",
        "cb_E+_43",
        "cb_E+_44",
        "cb_E+_45",
        "cb_E+_46",
        "cb_E+_47",
        "cb_E+_48",
        "cb_E+_49",
        "cb_E+_50",
        "cb_E+_51",
        "cb_E+_52",
        "cb_E+_53",
        "cb_E+_54",
        "cb_E+_55",
        "cb_E+_56",
        "cb_E+_57",
        "cb_E+_58",
        "cb_E+_59",
        "cb_E+_60",
        "cb_E+_61",
        "cb_E+_62",
        "cb_E+_63",
        "cb_E+_64",
        "cb_E+_65",
      ],
    },
    [Variante.Bonus]: {
      [Elternteil.Eins]: [
        "cb_PB_1",
        "cb_PB_2",
        "cb_PB_3",
        "cb_PB_4",
        "cb_PB_5",
        "cb_PB_6",
        "cb_PB_7",
        "cb_PB_8",
        "cb_PB_9",
        "cb_PB_10",
        "cb_PB_11",
        "cb_PB_12",
        "cb_PB_13",
        "cb_PB_14",
        "cb_PB_15",
        "cb_PB_16",
        "cb_PB_17",
        "cb_PB_18",
        "cb_PB_19",
        "cb_PB_20",
        "cb_PB_21",
        "cb_PB_22",
        "cb_PB_23",
        "cb_PB_24",
        "cb_PB_25",
        "cb_PB_26",
        "cb_PB_27",
        "cb_PB_28",
        "cb_PB_29",
        "cb_PB_30",
        "cb_PB_31",
        "cb_PB_32",
      ],
      [Elternteil.Zwei]: [
        "cb_PB_34",
        "cb_PB_35",
        "cb_PB_36",
        "cb_PB_37",
        "cb_PB_38",
        "cb_PB_39",
        "cb_PB_40",
        "cb_PB_41",
        "cb_PB_42",
        "cb_PB_43",
        "cb_PB_44",
        "cb_PB_45",
        "cb_PB_46",
        "cb_PB_47",
        "cb_PB_48",
        "cb_PB_49",
        "cb_PB_50",
        "cb_PB_51",
        "cb_PB_52",
        "cb_PB_53",
        "cb_PB_54",
        "cb_PB_55",
        "cb_PB_56",
        "cb_PB_57",
        "cb_PB_58",
        "cb_PB_59",
        "cb_PB_60",
        "cb_PB_61",
        "cb_PB_62",
        "cb_PB_63",
        "cb_PB_64",
        "cb_PB_65",
      ],
    },
  },
} as const;
