#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o verbose

cd ed-monatsplaner-app-develop
rm -rf ./node_modules ./build

npm install
npm run lint
npm test
npm run build

sudo npm link

cd ..

cd ed-egr-app-develop
rm -rf ./node_modules ./build

npm link @egr/monatsplaner-app
npm run test-all
npm run build

npm start
