import { Elternteil, Variante } from "@/monatsplaner";
import pdfFileAntrag from "@/pdfAntrag/assets/bis2024-03-31_antrag.pdf";
import pdfFileSeite from "@/pdfAntrag/assets/bis2024-03-31_seite.pdf";

export const pdfVersionVorApril2024 = {
  start: new Date("2020-01-01"),
  end: new Date("2024-03-31"),
  pdfFileAntragPath: pdfFileAntrag,
  pdfFileSeitePath: pdfFileSeite,
  fieldNames: {
    vorname: {
      [Elternteil.Eins]: "Vorname2B",
      [Elternteil.Zwei]: "Vorname2B_2",
    },
    [Variante.Basis]: {
      [Elternteil.Eins]: [
        "Basiselterngeld_01",
        "Basiselterngeld_02",
        "Basiselterngeld_03",
        "Basiselterngeld_04",
        "Basiselterngeld_05",
        "Basiselterngeld_06",
        "Basiselterngeld_07",
        "Basiselterngeld_08",
        "Basiselterngeld_09",
        "Basiselterngeld_10",
        "Basiselterngeld_11",
        "Basiselterngeld_12",
        "Basiselterngeld_13",
        "Basiselterngeld_14",
      ],
      [Elternteil.Zwei]: [
        "Basiselterngeld_01_aE",
        "Basiselterngeld_02_aE",
        "Basiselterngeld_03_aE",
        "Basiselterngeld_04_aE",
        "Basiselterngeld_05_aE",
        "Basiselterngeld_06_aE",
        "Basiselterngeld_07_aE",
        "Basiselterngeld_08_aE",
        "Basiselterngeld_09_aE",
        "Basiselterngeld_10_aE",
        "Basiselterngeld_11_aE",
        "Basiselterngeld_12_aE",
        "Basiselterngeld_13_aE",
        "Basiselterngeld_14_aE",
      ],
    },
    [Variante.Plus]: {
      [Elternteil.Eins]: [
        "Elterngeld_Plus_01",
        "Elterngeld_Plus_02",
        "Elterngeld_Plus_03",
        "Elterngeld_Plus_04",
        "Elterngeld_Plus_05",
        "Elterngeld_Plus_06",
        "Elterngeld_Plus_07",
        "Elterngeld_Plus_08",
        "Elterngeld_Plus_09",
        "Elterngeld_Plus_10",
        "Elterngeld_Plus_11",
        "Elterngeld_Plus_12",
        "Elterngeld_Plus_13",
        "Elterngeld_Plus_14",
        "Elterngeld_Plus_15",
        "Elterngeld_Plus_16",
        "Elterngeld_Plus_17",
        "Elterngeld_Plus_18",
        "Elterngeld_Plus_19",
        "Elterngeld_Plus_20",
        "Elterngeld_Plus_21",
        "Elterngeld_Plus_22",
        "Elterngeld_Plus_23",
        "Elterngeld_Plus_24",
        "Elterngeld_Plus_25",
        "Elterngeld_Plus_26",
        "Elterngeld_Plus_27",
        "Elterngeld_Plus_28",
        "Elterngeld_Plus_29",
        "Elterngeld_Plus_30",
        "Elterngeld_Plus_31",
        "Elterngeld_Plus_32",
      ],
      [Elternteil.Zwei]: [
        "Elterngeld_Plus_01_aE",
        "Elterngeld_Plus_02_aE",
        "Elterngeld_Plus_03_aE",
        "Elterngeld_Plus_04_aE",
        "Elterngeld_Plus_05_aE",
        "Elterngeld_Plus_06_aE",
        "Elterngeld_Plus_07_aE",
        "Elterngeld_Plus_08_aE",
        "Elterngeld_Plus_09_aE",
        "Elterngeld_Plus_10_aE",
        "Elterngeld_Plus_11_aE",
        "Elterngeld_Plus_12_aE",
        "Elterngeld_Plus_13_aE",
        "Elterngeld_Plus_14_aE",
        "Elterngeld_Plus_15_aE",
        "Elterngeld_Plus_16_aE",
        "Elterngeld_Plus_17_aE",
        "Elterngeld_Plus_18_aE",
        "Elterngeld_Plus_19_aE",
        "Elterngeld_Plus_20_aE",
        "Elterngeld_Plus_21_aE",
        "Elterngeld_Plus_22_aE",
        "Elterngeld_Plus_23_aE",
        "Elterngeld_Plus_24_aE",
        "Elterngeld_Plus_25_aE",
        "Elterngeld_Plus_26_aE",
        "Elterngeld_Plus_27_aE",
        "Elterngeld_Plus_28_aE",
        "Elterngeld_Plus_29_aE",
        "Elterngeld_Plus_30_aE",
        "Elterngeld_Plus_31_aE",
        "Elterngeld_Plus_32_aE",
      ],
    },
    [Variante.Bonus]: {
      [Elternteil.Eins]: [
        "Partnerschaftsbonus_01",
        "Partnerschaftsbonus_02",
        "Partnerschaftsbonus_03",
        "Partnerschaftsbonus_04",
        "Partnerschaftsbonus_05",
        "Partnerschaftsbonus_06",
        "Partnerschaftsbonus_07",
        "Partnerschaftsbonus_08",
        "Partnerschaftsbonus_09",
        "Partnerschaftsbonus_10",
        "Partnerschaftsbonus_11",
        "Partnerschaftsbonus_12",
        "Partnerschaftsbonus_13",
        "Partnerschaftsbonus_14",
        "Partnerschaftsbonus_15",
        "Partnerschaftsbonus_16",
        "Partnerschaftsbonus_17",
        "Partnerschaftsbonus_18",
        "Partnerschaftsbonus_19",
        "Partnerschaftsbonus_20",
        "Partnerschaftsbonus_21",
        "Partnerschaftsbonus_22",
        "Partnerschaftsbonus_23",
        "Partnerschaftsbonus_24",
        "Partnerschaftsbonus_25",
        "Partnerschaftsbonus_26",
        "Partnerschaftsbonus_27",
        "Partnerschaftsbonus_28",
        "Partnerschaftsbonus_29",
        "Partnerschaftsbonus_30",
        "Partnerschaftsbonus_31",
        "Partnerschaftsbonus_32",
      ],
      [Elternteil.Zwei]: [
        "Partnerschaftsbonus_01_aE",
        "Partnerschaftsbonus_02_aE",
        "Partnerschaftsbonus_03_aE",
        "Partnerschaftsbonus_04_aE",
        "Partnerschaftsbonus_05_aE",
        "Partnerschaftsbonus_06_aE",
        "Partnerschaftsbonus_07_aE",
        "Partnerschaftsbonus_08_aE",
        "Partnerschaftsbonus_09_aE",
        "Partnerschaftsbonus_10_aE",
        "Partnerschaftsbonus_11_aE",
        "Partnerschaftsbonus_12_aE",
        "Partnerschaftsbonus_13_aE",
        "Partnerschaftsbonus_14_aE",
        "Partnerschaftsbonus_15_aE",
        "Partnerschaftsbonus_16_aE",
        "Partnerschaftsbonus_17_aE",
        "Partnerschaftsbonus_18_aE",
        "Partnerschaftsbonus_19_aE",
        "Partnerschaftsbonus_20_aE",
        "Partnerschaftsbonus_21_aE",
        "Partnerschaftsbonus_22_aE",
        "Partnerschaftsbonus_23_aE",
        "Partnerschaftsbonus_24_aE",
        "Partnerschaftsbonus_25_aE",
        "Partnerschaftsbonus_26_aE",
        "Partnerschaftsbonus_27_aE",
        "Partnerschaftsbonus_28_aE",
        "Partnerschaftsbonus_29_aE",
        "Partnerschaftsbonus_30_aE",
        "Partnerschaftsbonus_31_aE",
        "Partnerschaftsbonus_32_aE",
      ],
    },
  },
} as const;
