export type Subtable = {
  label: string;
  nb_uniq_visitors: number;
  nb_visits: number | string;
  nb_events: number | string;
  nb_events_with_value: number | string;
  sum_event_value: number;
  min_event_value: number;
  max_event_value: number;
  avg_event_value: number;
};

export type Action = {
  label: string;
  nb_uniq_visitors: number;
  nb_visits: string | number;
  nb_events: string | number;
  nb_events_with_value: string | number;
  sum_event_value: number;
  min_event_value: number;
  max_event_value: number;
  avg_event_value: number;
  idsubdatatable: number;
  segment: string;
  subtable: Subtable[] | null;
};

export type EventModuleMethod = "Events.getAction";

export type MetadataModuleMethod = "API.get";

export type Method = MetadataModuleMethod | EventModuleMethod;

export type Metadata = {
  nb_uniq_visitors: number;
  nb_visits: number;
  nb_users: number;
  nb_actions: number;
  max_actions: number;
  bounce_count: number;
  sum_visit_length: number;
  nb_visits_new: number;
  nb_actions_new: number;
  nb_uniq_visitors_new: number;
  nb_users_new: number;
  max_actions_new: number;
  bounce_rate_new: string;
  nb_actions_per_visit_new: number;
  avg_time_on_site_new: string;
  nb_visits_returning: number;
  nb_actions_returning: number;
  nb_uniq_visitors_returning: number;
  nb_users_returning: number;
  max_actions_returning: number;
  bounce_rate_returning: string;
  nb_actions_per_visit_returning: number;
  avg_time_on_site_returning: string;
  Referrers_visitorsFromSearchEngines: number;
  Referrers_visitorsFromSocialNetworks: number;
  Referrers_visitorsFromDirectEntry: number;
  Referrers_visitorsFromWebsites: number;
  Referrers_visitorsFromCampaigns: number;
  Referrers_distinctSearchEngines: number;
  Referrers_distinctSocialNetworks: number;
  Referrers_distinctKeywords: number;
  Referrers_distinctWebsites: number;
  Referrers_distinctWebsitesUrls: number;
  Referrers_distinctCampaigns: number;
  PagePerformance_network_time: number;
  PagePerformance_network_hits: number;
  PagePerformance_servery_time: number;
  PagePerformance_server_hits: number;
  PagePerformance_transfer_time: number;
  PagePerformance_transfer_hits: number;
  PagePerformance_domprocessing_time: number;
  PagePerformance_domprocessing_hits: number;
  PagePerformance_domcompletion_time: number;
  PagePerformance_domcompletion_hits: number;
  PagePerformance_onload_time: number;
  PagePerformance_onload_hits: number;
  PagePerformance_pageload_time: number;
  PagePerformance_pageload_hits: number;
  avg_time_network: string;
  avg_time_server: string;
  avg_time_transfer: string;
  avg_time_dom_processing: string;
  avg_time_dom_completion: string;
  avg_time_on_load: string;
  avg_page_load_time: string;
  nb_conversions: number;
  nb_visits_converted: number;
  revenue: number;
  conversion_rate: string;
  nb_conversions_new_visit: number;
  nb_visits_converted_new_visit: number;
  revenue_new_visit: number;
  conversion_rate_new_visit: string;
  nb_conversions_returning_visit: number;
  nb_visits_converted_returning_visit: number;
  revenue_returning_visit: number;
  conversion_rate_returning_visit: string;
  nb_form_views: number;
  nb_form_viewers: number;
  nb_form_starts: number;
  nb_form_starters: number;
  nb_form_submissions: number;
  nb_form_submitters: number;
  nb_form_resubmitters: number;
  nb_form_conversions: number;
  nb_pageviews: number;
  nb_uniq_pageviews: number;
  nb_downloads: number;
  nb_uniq_downloads: number;
  nb_outlinks: number;
  nb_uniq_outlinks: number;
  nb_searches: number;
  nb_keywords: number;
  Referrers_visitorsFromDirectEntry_percent: string;
  Referrers_visitorsFromSearchEngines_percent: string;
  Referrers_visitorsFromCampaigns_percent: string;
  Referrers_visitorsFromSocialNetworks_percent: string;
  Referrers_visitorsFromWebsites_percent: string;
  bounce_rate: string;
  nb_actions_per_visit: number;
  avg_time_on_site: string;
  form_starters_rate: string;
  form_submitter_rate: string;
  form_conversion_rate: string;
  form_resubmitters_rate: string;
  avg_form_time_hesitation: string;
  avg_form_time_spent: string;
  avg_form_time_to_first_submission: string;
  avg_form_time_to_conversion: string;
};
