export const TAG_IN_MS = 1000 * 60 * 60 * 24;
export const MUTTERSCHUTZ_TAGE_VOR_GEBURT_STANDARD = 6 * 7;
export const MUTTERSCHUTZ_TAGE_NACH_GEBURT_STANDARD = 8 * 7;
export const MUTTERSCHUTZ_TAGE_NACH_GEBURT_VERLAENGERT = 12 * 7;
export const MUTTERSCHUTZ_DAUER_GESAMT_STANDARD = 14 * 7;
export const MUTTERSCHUTZ_DAUER_GESAMT_VERLAENGERT = 18 * 7;
