export enum KassenArt {
  // Angestellte, Selbstständige
  GESETZLICH_PFLICHTVERSICHERT = "GESETZLICH_PFLICHTVERSICHERT",

  // Sonstige
  NICHT_GESETZLICH_PFLICHTVERSICHERT = "NICHT_GESETZLICH_PFLICHTVERSICHERT",
}
