export const F_FAKTOR = 0.7509;
export const SATZ_KVPV_BEEG = 0.09;
export const SATZ_RV_BEEG = 0.1;
export const SATZ_ALV_BEEG = 0.02;
export const MIN_GESCHWISTERBONUS = 75;
export const RATE_BONUS = 0.1;
export const MINDESTSATZ = 300; // TODO: get rid off
export const GRENZE_MINI_MIDI = 520;
export const GRENZE_MIDI_MAX = 1300;
export const MAX_EINKOMMEN = 175_000;
