export enum ElternGeldKategorie {
  KEIN_ELTERN_GELD,
  BASIS_ELTERN_GELD,
  BASIS_ELTERN_GELD_MIT_ERWERBS_TAETIGKEIT,
  ELTERN_GELD_PLUS_OHNE_ERWERBS_TAETIGKEIT,
  ELTERN_GELD_PLUS_MIT_ERWERBS_TAETIGKEIT,
}
