import {
  type Antragstellende,
  type MonatlichesBrutto,
  YesNo,
} from "@/application/features/abfrageteil/state";
import { bundeslaender } from "@/application/features/pdfAntrag";
import { KassenArt, KinderFreiBetrag, Steuerklasse } from "@/elterngeldrechner";

export const preloadedState = {
  stepAllgemeineAngaben: {
    bundesland: bundeslaender[2].name,
    antragstellende: "FuerBeide" as Antragstellende,
    pseudonym: {
      ET1: "Jasper Darwin Artus",
      ET2: "Salomé Loreley Zoe",
    },
    alleinerziehend: YesNo.NO,
    mutterschutz: YesNo.NO,
  },
  stepNachwuchs: {
    anzahlKuenftigerKinder: 1,
    wahrscheinlichesGeburtsDatum: "01.04.2025",
    geschwisterkinder: [
      {
        geburtsdatum: "24.10.2019",
        istBehindert: false,
      },
    ],
  },
  stepErwerbstaetigkeit: {
    ET1: {
      vorGeburt: YesNo.YES,
      isNichtSelbststaendig: true,
      isSelbststaendig: true,
      sozialVersicherungsPflichtig: YesNo.YES,
      monatlichesBrutto: "MehrAlsMiniJob" as MonatlichesBrutto,
      mehrereTaetigkeiten: YesNo.NO,
    },
    ET2: {
      vorGeburt: YesNo.YES,
      isNichtSelbststaendig: true,
      isSelbststaendig: false,
      sozialVersicherungsPflichtig: YesNo.YES,
      monatlichesBrutto: "MehrAlsMiniJob" as MonatlichesBrutto,
      mehrereTaetigkeiten: YesNo.NO,
    },
  },
  stepEinkommen: {
    antragstellende: "FuerBeide" as Antragstellende,
    limitEinkommenUeberschritten: YesNo.NO,
    ET1: {
      istErwerbstaetig: YesNo.YES,
      hasMischEinkommen: YesNo.NO,
      istSelbststaendig: false,
      istNichtSelbststaendig: true,
      bruttoEinkommenNichtSelbstaendig: {
        type: "average" as const,
        average: null,
        perYear: null,
        perMonth: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      steuerklasse: Steuerklasse.III,
      splittingFaktor: null,
      kinderFreiBetrag: KinderFreiBetrag.ZKF1,
      gewinnSelbstaendig: {
        type: "average" as const,
        average: null,
        perYear: null,
        perMonth: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      rentenVersicherung: null,
      zahlenSieKirchenSteuer: YesNo.YES,
      kassenArt: KassenArt.GESETZLICH_PFLICHTVERSICHERT,
      taetigkeitenNichtSelbstaendigUndSelbstaendig: [
        {
          artTaetigkeit: "NichtSelbststaendig" as const,
          bruttoEinkommenDurchschnitt: 1000,
          isMinijob: YesNo.YES,
          zeitraum: [
            { from: "1", to: "3" },
            { from: "6", to: "9" },
          ],
          versicherungen: {
            hasRentenversicherung: true,
            hasArbeitslosenversicherung: false,
            hasKrankenversicherung: true,
            none: false,
          },
        },
        {
          artTaetigkeit: "Selbststaendig" as const,
          gewinneinkuenfte: 24000,
          versicherungen: {
            hasRentenversicherung: true,
            hasArbeitslosenversicherung: false,
            hasKrankenversicherung: true,
            none: false,
          },
        },
      ],
    },
    ET2: {
      istErwerbstaetig: YesNo.YES,
      hasMischEinkommen: YesNo.NO,
      istSelbststaendig: false,
      istNichtSelbststaendig: true,
      bruttoEinkommenNichtSelbstaendig: {
        type: "monthly" as const,
        average: null,
        perYear: null,
        perMonth: [
          800, 900, 1000, 800, 2000, 1200, 1500, 1300, 1000, 1800, 1600, 2500,
        ],
      },
      steuerklasse: Steuerklasse.I,
      splittingFaktor: null,
      kinderFreiBetrag: KinderFreiBetrag.ZKF1,
      gewinnSelbstaendig: {
        type: "average" as const,
        average: null,
        perYear: null,
        perMonth: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      rentenVersicherung: null,
      zahlenSieKirchenSteuer: YesNo.NO,
      kassenArt: KassenArt.GESETZLICH_PFLICHTVERSICHERT,
      taetigkeitenNichtSelbstaendigUndSelbstaendig: [],
    },
  },
};
