name: "Fetch version hash"
description: "Sets up playwright, loads the given url and extracts the version hash variable"

inputs:
  url:
    description: "The url on which the app is running"
    required: true

outputs:
  version-hash:
    description: "The commit hash of the current deployment"
    value: ${{ steps.playwright.outputs.version-hash }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/cached-node-install
      with:
        directory: "./.github/actions/fetch-version-hash"

    - name: Install browsers
      uses: ./.github/actions/cached-playwright-setup
      with:
        directory: "./.github/actions/fetch-version-hash"

    - id: playwright
      name: Run Playwright script
      working-directory: .github/actions/fetch-version-hash
      run: node index.js ${{ inputs.url }}
      shell: bash
