export enum ErwerbsArt {
  NEIN = "NEIN",
  JA_SELBSTSTAENDIG = "JA_SELBSTSTAENDIG",
  JA_NICHT_SELBST_MIT_SOZI = "JA_NICHT_SELBST_MIT_SOZI",
  JA_NICHT_SELBST_MINI = "JA_NICHT_SELBST_MINI",
  JA_NICHT_SELBST_OHNE_SOZI = "JA_NICHT_SELBST_OHNE_SOZI",
  JA_MISCHEINKOMMEN = "JA_MISCHEINKOMMEN",
}
