name: Production Redeploy (Tag or SHA)

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  redeploy:
    runs-on: ubuntu-24.04
    environment: production
    timeout-minutes: 20
    env:
      MISE_ENV: production

    steps:
      - name: Checkout ref
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - uses: ./.github/actions/setup-toolchain

      - name: Deploy to the production environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STACKIT_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STACKIT_SECRET_ACCESS_KEY }}
          VITE_BUILD_VERSION: ${{ github.sha }}
        run: mise run deploy

      - name: Track deployment
        uses: digitalservicebund/track-deployment@5a2815e150e1268983aac5ca04c8c046ed1b614a
        with:
          project: elterngeldrechner
          environment: production
          metrics_deployment_webhook_url: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
          metrics_webhook_token: ${{ secrets.METRICS_WEBHOOK_TOKEN }}
