name: Production Redeploy (Tag or SHA)

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  redeploy:
    runs-on: ubuntu-24.04
    environment: production
    timeout-minutes: 20

    steps:
      - name: Checkout ref
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - uses: ./.github/actions/setup-toolchain

      - name: Run build specific for stack it production environment
        run: npm run build:production
        env:
          VITE_BASE_PATH: https://egr-assets-production.object.storage.eu01.onstackit.cloud/
          VITE_BUILD_VERSION: ${{ github.sha }}
          VITE_PUBLIC_POSTHOG_HOST: https://ph-proxy.prod.tech.digitalservice.dev
          VITE_PUBLIC_POSTHOG_PROJECT_TOKEN: phc_rUbW5TOq15FHTu5PoKh3g4uCJNNN7MvHu2WJPUIjEpa

      - name: Check build artifact structure
        run: scripts/check-build-artifacts.sh

      - name: Synchronize build output with object storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STACKIT_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STACKIT_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: https://object.storage.eu01.onstackit.cloud
        run: |
          aws s3 sync dist/assets/ s3://egr-assets-production/assets/ --exclude "index-*.js"
          aws s3 cp dist/assets/index-*.js s3://egr-assets-production/index.js --cache-control "max-age=0, no-cache, no-store, must-revalidate"

      - name: Track deployment
        uses: digitalservicebund/track-deployment@5a2815e150e1268983aac5ca04c8c046ed1b614a
        with:
          project: elterngeldrechner
          environment: production
          metrics_deployment_webhook_url: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
          metrics_webhook_token: ${{ secrets.METRICS_WEBHOOK_TOKEN }}
