name: Deploy Preview

on:
  workflow_dispatch:
    inputs:
      name:
        description: The name used to publish the feature. The preview will be accessible at $domain/preview/$name.
        required: true
        type: string
      enable_new_abfrageteil:
        description: "Neuen Abfrageteil verwenden?"
        required: false
        type: boolean
        default: false

  workflow_call:
    inputs:
      name:
        description: The name used to publish the feature. The preview will be accessible at $domain/preview/$name.
        required: true
        type: string
      enable_new_abfrageteil:
        required: false
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/cached-node-install

      - name: Run preview build specific for stack it staging environment
        run: npm run build:staging
        env:
          VITE_BASE_PATH: https://egr-assets-staging.object.storage.eu01.onstackit.cloud/preview/${{ inputs.name }}/
          VITE_FEATURE_FLAG_ABFRAGETEIL_V2: ${{ inputs.enable_new_abfrageteil }}

      - name: Synchronize build output with object storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STACKIT_STAGING_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STACKIT_STAGING_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.STACKIT_S3_ENDPOINT_URL }}
          PREVIEW_NAME: ${{ inputs.name }}
        run: aws s3 sync dist/ "s3://egr-assets-staging/preview/${PREVIEW_NAME}" --cache-control "max-age=0, no-cache, no-store, must-revalidate"

      - name: Add Preview Link to Summary
        if: success()
        env:
          PREVIEW_NAME: ${{ inputs.name }}
        run: |
          {
            echo "### Preview Deployment erfolgreich!"
            echo ""
            echo "Die Preview-Version ist jetzt unter folgendem Link erreichbar:"
            echo "[https://assets.elterngeldrechner.dev.tech.digitalservice.dev/preview/${PREVIEW_NAME}/index.html](https://assets.elterngeldrechner.dev.tech.digitalservice.dev/preview/${PREVIEW_NAME}/index.html)"
          } >> $GITHUB_STEP_SUMMARY
