name: Undeploy Preview

permissions: {}

on:
  workflow_dispatch:
    inputs:
      name:
        description: The name originally used to publish the preview, corresponding to the final path segment of $domain/preview/<name>.
        required: true
        type: string

  workflow_call:
    inputs:
      name:
        description: The name originally used to publish the preview, corresponding to the final path segment of $domain/preview/<name>.
        required: true
        type: string

jobs:
  undeploy:
    runs-on: ubuntu-24.04
    environment: staging
    steps:
      - name: Remove preview deployment from object storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STACKIT_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STACKIT_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.STACKIT_S3_ENDPOINT_URL }}
          PREVIEW_NAME: ${{ inputs.name }}
        run: aws s3 rm "s3://egr-assets-staging/preview/${PREVIEW_NAME}" --recursive
